---
- name: Download etcd files
  become: true
  ansible.builtin.get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.5.14/etcd-v3.5.14-linux-amd64.tar.gz
    dest: /home/rsamigullin/etcd-v3.5.14-linux-amd64.tar.gz
    mode: '0666'

- name: Unarchive a file that is already on the remote machine
  become: true
  ansible.builtin.unarchive:
    src: /home/rsamigullin/etcd-v3.5.14-linux-amd64.tar.gz
    dest: /home/rsamigullin/
    remote_src: yes

- name: Copy etcd files
  become: true
  ansible.builtin.copy:
    src: "/home/rsamigullin/etcd-v3.5.14-linux-amd64/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: '755'
  loop:
     - etcd
     - etcdctl
     - etcdutl

- name: delivery etcd config
  become: true
  ansible.builtin.template:
    src: etcd.j2
    dest: /etc/default/etcd
    mode: '0644'

- name: delivery etcd service
  become: true
  ansible.builtin.template:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service

- name: Ensure group "etcd" exists
  become: true
  ansible.builtin.group:
    name: etcd
    state: present

- name: Create a user 'etcd'
  become: true
  ansible.builtin.user:
    name: etcd
    create_home: no
    group: etcd

- name: create etcd default directory
  become: true
  ansible.builtin.file:
    path: "/var/lib/etcd"
    state: directory
    recurse: yes
    owner: etcd
    group: etcd

- name: create etcd database directory
  become: true
  ansible.builtin.file:
    path: "/var/lib/etcd/default"
    state: directory
    recurse: yes
    owner: etcd
    group: etcd

- name: reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: etcd service restart
  become: true
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: etcd