---
- name: install haproxy
  become: true
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: delivery haproxy config
  become: true
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: restart and enable haproxy service
  become: true
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
    enabled: true
